name: .NET Framework Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: GitHubActionsWinFormTest.sln
      Project_Directory: GitHubActionsWinFormTest
      Project_Path: GitHubActionsWinFormTest.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild $env:Solution_Name /p:Configuration=Release -p:OutDir="out/"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Result
        path: ${{ env.Wap_Project_Directory }}\out
